pipeline {
	agent any
	tools{
	    maven "Maven 3.8.0"
	}
	stages {

		stage("Jenkins: build") {
			steps {
			    script{
                    sh "mvn clean package -DskipTests=true"
				}
			}
		}
    }
}			
